apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque  # key value secret type
data:
  # echo -n "username" | base64
  mongo-root-username: dXNlcm5hbWU=
  # echo -n "password" | base64
  mongo-root-password: cGFzc3dvcmQ=
