apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.url  }}
      secretName: default-tls-secret
  rules:
    - host: {{ .Values.ingress.url  }}
      http:
        paths:
          - backend:
              serviceName: {{ .Values.service.name }}
              servicePort: {{ .Values.ingress.servicePort}}